export const COMMS_STARTED = '[Comms] Starting connection'
export const COMMS_TIMEOUT = '[Comms] Connection timed out'
export const COMMS_CLOSED = '[Comms] Connection closed'
export const COMMS_WELCOME = '[Comms] Received Welcome Message'
export const COMMS_WEBRTC_ICE_CANDIDATE = '[Comms] Received ICE Candidate'
export const COMMS_WEBRTC_ICE_OFFER = '[Comms] Received ICE Offer'
export const COMMS_WEBRTC_ICE_ANSWER = '[Comms] Received ICE Candidate'
export const COMMS_WEBRTC_SIGNALING_STATE = '[Comms] Signaling State Change'
export const COMMS_WEBRTC_ICE_STATE = '[Comms] ICE State Change'
export const COMMS_WEBRTC_ERROR = '[Comms] WebRTC Error'
export const COMMS_DATACHANNEL_RELIABLE = '[Comms] Reliable Channel Acquired'
export const COMMS_DATACHANNEL_UNRELIABLE = '[Comms] Unreliable Channel Acquired'
export const COMMS_DATACHANNEL_RELIABLE_LOST = '[Comms] Reliable Channel Lost'
export const COMMS_DATACHANNEL_UNRELIABLE_LOST = '[Comms] Unreliable Channel Lost'
export const COMMS_CREDENTIALS_REQUEST = '[Comms] Getting Credentials'
export const COMMS_CREDENTIALS_ACQUIRED = '[Comms] Credentials Obtained'
export const COMMS_REQUEST_AUTHENTICATION = '[Comms] Sending Authentication'
export const COMMS_SUCCESS_AUTHENTICATION = '[Comms] Successfully Authenticated'
export const COMMS_FAILURE_AUTHENTICATION = '[Comms] Failure Authenticating'

export const PROTOCOL_POSITION = '[Protocol:In] Position update'
export const PROTOCOL_PROFILE = '[Protocol:In] Profile update'
export const PROTOCOL_PING = '[Protocol:In] Ping'
export const PROTOCOL_CHAT = '[Protocol:In] Chat message'
export const PROTOCOL_SCENE = '[Protocol:In] Scene event'

export const PROTOCOL_OUT_POSITION = '[Protocol:Out] Position update'
export const PROTOCOL_OUT_PROFILE = '[Protocol:Out] Profile update'
export const PROTOCOL_OUT_PING = '[Protocol:Out] Ping'
export const PROTOCOL_OUT_CHAT = '[Protocol:Out] Chat message'
export const PROTOCOL_OUT_SCENE = '[Protocol:Out] Scene event'

export const PROTOCOL_SUBSCRIPTION = '[Protocol] Requesting topic subscription'
export const PROTOCOL_UNSUBSCRIBE = '[Protocol] Removing subscription'
