export const LIST_WEARABLE_ASSET_PACKS_REQUEST = "LIST_WEARABLE_ASSET_PACKS_REQUEST"
export const LIST_WEARABLE_ASSET_PACKS_SUCCESS = "LIST_WEARABLE_ASSET_PACKS_SUCCESS"
export const LIST_WEARABLE_ASSET_PACKS_FAILURE = "LIST_WEARABLE_ASSET_PACKS_FAILURE"

export const BASE_WEARABLES_REQUEST = "BASE_WEARABLES_REQUEST"
export const BASE_WEARABLES_SUCCESS = "BASE_WEARABLES_SUCCESS"
export const BASE_WEARABLES_FAILURE = "BASE_WEARABLES_FAILURE"

export const WEARABLE_ASSET_PACK_REQUEST = "WEARABLE_ASSET_PACK_REQUEST"
export const WEARABLE_ASSET_PACK_SUCCESS = "WEARABLE_ASSET_PACK_SUCCESS"
export const WEARABLE_ASSET_PACK_FAILURE = "WEARABLE_ASSET_PACK_FAILURE"

export const WEARABLE_VALIDATE_PERMISSION_REQUEST = "WEARABLE_VALIDATE_PERMISSION_REQUEST"
export const WEARABLE_VALIDATE_PERMISSION_SUCCESS = "WEARABLE_VALIDATE_PERMISSION_SUCCESS"
export const WEARABLE_VALIDATE_PERMISSION_FAILURE = "WEARABLE_VALIDATE_PERMISSION_FAILURE"

export const WEARABLE_INVENTORY_REQUEST = "WEARABLE_INVENTORY_REQUEST"
export const WEARABLE_INVENTORY_SUCCESS = "WEARABLE_INVENTORY_SUCCESS"
export const WEARABLE_INVENTORY_FAILURE = "WEARABLE_INVENTORY_FAILURE"

export const WEARABLE_EQUIP_REQUEST = "WEARABLE_EQUIP_REQUEST"
export const WEARABLE_EQUIP_SUCCESS = "WEARABLE_EQUIP_SUCCESS"
export const WEARABLE_EQUIP_FAILURE = "WEARABLE_EQUIP_FAILURE"

export const WEARABLE_ADD_TO_INVENTORY_REQUEST = "WEARABLE_ADD_TO_INVENTORY_REQUEST"
export const WEARABLE_ADD_TO_INVENTORY_SUCCESS = "WEARABLE_ADD_TO_INVENTORY_SUCCESS"
export const WEARABLE_ADD_TO_INVENTORY_FAILURE = "WEARABLE_ADD_TO_INVENTORY_FAILURE"

export const WEARABLE_DISCARD_FROM_INVENTORY_REQUEST = "WEARABLE_DISCARD_FROM_INVENTORY_REQUEST"
export const WEARABLE_DISCARD_FROM_INVENTORY_SUCCESS = "WEARABLE_DISCARD_FROM_INVENTORY_SUCCESS"
export const WEARABLE_DISCARD_FROM_INVENTORY_FAILURE = "WEARABLE_DISCARD_FROM_INVENTORY_FAILURE"
