// tslint:disable: no-commented-out-code
import Auth from 'decentraland-auth'

import { Profile } from './types'

/**
 * The profiles of all the near players
 */
export let profiles = new Map<string, Profile>()

/**
 * The profile of the current player
 */
let localProfile: Profile | null = null

export async function initializeProfile(auth: Auth): Promise<Profile> {
  let request = await auth.getRequest('https://profile.decentraland.zone/api/v1/profile')
  let response = await fetch(request)
  // TODO Should we create a default profile is not created? Maybe autogenerate one?
  if (response.status === 404) {
    // request = await auth.getRequest('https://profile.decentraland.zone/api/v1/profile', {
    //   method: 'POST',
    //   body: JSON.stringify({
    //     name: 'some-name',
    //     description: 'Some description'
    //   })
    // })
    // response = await fetch(request)
  } else {
    localProfile = await response.json()
  }
  return localProfile
}

/**
 * Returns current profile either retrieved from DCL profile service
 * or autogenerated for a guest/new session
 */
export function getCurrentProfile(): Profile {
  if (localProfile === null) {
    throw new Error('Profile was not initialized')
  }

  return localProfile
}
